### ISSUE TITLE
在 vue-cli 升级 webpack5 使用 ModuleFederationPlugin 报错

### ISSUE THREAD

**Issue by lhlGitHub** [efoxTeam/emp#113]
ERROR  TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
    at ModuleFederationPlugin.apply (E:\2020project\activity-static\202102\node_modules\_webpack@5.28.0@webpack\lib\container\ModuleFederationPlugin.js:45:49)
    at webpack (E:\2020project\activity-static\202102\node_modules\_webpack@4.46.0@webpack\lib\webpack.js:51:13)
    at serve (E:\2020project\activity-static\202102\node_modules\_@vue_cli-service@4.5.12@@vue\cli-service\lib\commands\serve.js:163:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by ckken** [comment]
可以发到 vue cli 官方问问
