### ISSUE TITLE
Vue  工程导入这个"@efox/emp-cli": "1.8.10" 启动报错

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#123]
(node:12408) UnhandledPromiseRejectionWarning: Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:373:10)
    at RuleSetCompiler.compileCondition (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:309:17)
    at ruleSetCompiler.hooks.rule.tap (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\BasicMatcherRulePlugin.js:29:40)
    at Hook.eval [as call] (eval at create (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:17:1)
    at RuleSetCompiler.compileRule (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:177:19)
    at rules.map (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:184:30)
    at rules.map (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compile (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\NormalModuleFactory.js:238:34)
    at Compiler.createNormalModuleFactory (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:1020:31)
    at Compiler.newCompilationParams (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:1040:30)
(node:12408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (r
ejection id: 1)

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/issues/124 重复
