### ISSUE TITLE
 @efox/emp-cli  版本问题，Vue导入报错，不知道什么原因

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#124]
Done in 16.97s.
yarn run v1.22.10
$ emp dev
╔════════════════════╤═══════════════╗
║ Emp & Deps         │ Version       ║
╟────────────────────┼───────────────╢
║ @efox/emp-cli      │ 1.8.10        ║
╟────────────────────┼───────────────╢
║ webpack            │ ^5.28.0       ║
╟────────────────────┼───────────────╢
║ webpack-dev-server │ ^4.0.0-beta.1 ║
╟────────────────────┼───────────────╢
║ typescript         │ ^4.1.3        ║
╟────────────────────┼───────────────╢
║ postcss            │ ^8.2.8        ║
╚════════════════════╧═══════════════╝

config { host: 'localhost',
  port: 6007,
  publicPath: 'http://localhost:6007/' }

* Webpack █████████████████████████ setup (3%)
 watch run

(node:15148) UnhandledPromiseRejectionWarning: Error: Compiling RuleSet failed: Unexpected property test in conditi
on (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.j
s:373:10)
    at RuleSetCompiler.compileCondition (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSe
tCompiler.js:309:17)
    at ruleSetCompiler.hooks.rule.tap (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\BasicMat
cherRulePlugin.js:29:40)
    at Hook.eval [as call] (eval at create (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\tapable\lib\HookCodeF
actory.js:19:10), <anonymous>:17:1)
    at RuleSetCompiler.compileRule (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetComp
iler.js:177:19)
    at rules.map (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCom
piler.js:153:16)
    at RuleSetCompiler.compileRule (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetComp
iler.js:184:30)
    at rules.map (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCom
piler.js:153:16)
    at RuleSetCompiler.compile (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler
.js:68:22)
    at new NormalModuleFactory (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\NormalModuleFactory.j
s:238:34)
    at Compiler.createNormalModuleFactory (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.j
s:1020:31)
    at Compiler.newCompilationParams (D:\toB\ui\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:104
0:30)
(node:15148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 (rejection id: 1)
(node:15148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje
ctions that are not handled will terminate the Node.js process with a non-zero exit code.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:6007/, http://127.0.0.1:6007/
<i> [webpack-dev-server] Content not from webpack is served from 'D:\toB\ui\public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
Starting server on http://localhost:6007
<i> [webpack-dev-middleware] wait until bundle finished: /

**Comment by longkehuawei** [comment]
是什么问题呀
