### ISSUE TITLE
新建一个vue脚手架工程，package.json 文件如下，集成emp 报错了

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#125]
{
  "name": "hello",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "dev": "emp dev",
    "build": "emp build --env prod",
    "start": "emp serve",
    "stat": "emp build --analyze",
    "emp": "emp",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11",
    "@efox/emp-cli": "latest",
    "@efox/emp-vue2": "latest"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

运行yarn & yarn dev 报错如下

D:\vue\vue-demo\vue-demo2\hello>yarn & yarn dev
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.76s.
yarn run v1.22.10
$ emp dev
╔════════════════════╤═══════════════╗
║ Emp & Deps         │ Version       ║
╟────────────────────┼───────────────╢
║ @efox/emp-cli      │ 1.6.17        ║
╟────────────────────┼───────────────╢
║ webpack            │ ^5.14.0       ║
╟────────────────────┼───────────────╢
║ webpack-dev-server │ ^4.0.0-beta.0 ║
╟────────────────────┼───────────────╢
║ typescript         │ ^4.1.3        ║
╟────────────────────┼───────────────╢
║ postcss            │ ^8.2.1        ║
╚════════════════════╧═══════════════╝

config { host: 'localhost',
  port: 6008,
  publicPath: 'http://localhost:6008/' }

* Webpack █████████████████████████ setup (3%)
 watch run

(node:16668) UnhandledPromiseRejectionWarning: Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:373:10)
    at RuleSetCompiler.compileCondition (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:309:17)
    at ruleSetCompiler.hooks.rule.tap (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\BasicMatcherRulePlugin.js:29:40)
    at Hook.eval [as call] (eval at create (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:17:1)
    at RuleSetCompiler.compileRule (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:177:19)
    at rules.map (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:184:30)
    at rules.map (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compile (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\NormalModuleFactory.js:226:34)
    at Compiler.createNormalModuleFactory (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:996:31)
    at Compiler.newCompilationParams (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:1016:30)
(node:16668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rej
ection id: 1)
(node:16668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<i> [webpack-dev-server] Project is running at http://127.0.0.1:6008/
<i> [webpack-dev-server] Content not from webpack is served from D:\vue\vue-demo\vue-demo2\hello\public
<i> [webpack-dev-server] 404s will fallback to /index.html
Starting server on http://localhost:6008
<i> [webpack-dev-middleware] wait until bundle finished: /

**Comment by flyyuan** [comment]
emp-config.js 也发一下

**Comment by longkehuawei** [comment]
emp-config.js  如下

const path = require('path')
const {VueLoaderPlugin} = require('vue-loader')
//
const ProjectRootPath = path.resolve('./')
// const packagePath = path.join(ProjectRootPath, 'package.json')
// const {dependencies} = require(packagePath)
//
const {getConfig} = require(path.join(ProjectRootPath, './src/config'))
//
module.exports = ({config, env, empEnv}) => {
  const confEnv = env === 'production' ? 'prod' : 'dev'
  const conf = getConfig(empEnv || confEnv)
  console.log('config', conf)
  //
  const srcPath = path.resolve('./src')
  config.entry('index').clear().add(path.join(srcPath, 'main.js'))
  //
  config.resolve.alias.set('vue', '@vue/runtime-dom')
  config.plugin('vue').use(VueLoaderPlugin, [])
  config.module
    .rule('vue')
    .test(/\.vue$/)
    .use('vue-loader')
    .loader('vue-loader')
  //
  const host = conf.host
  const port = conf.port
  const projectName = 'vueComponents'
  const publicPath = conf.publicPath || 'dist'
  config.output.publicPath(publicPath)
  config.devServer.port(port)
  //
  config.plugin('mf').tap(args => {
    args[0] = {
      ...args[0],
      ...{
        name: projectName,
        library: {type: 'var', name: projectName},
        filename: 'emp.js',
        remotes: {
          empReactBase: 'empReactBase',
        }, 
        exposes: {
          './Content.vue': './src/components/Content',
        },
        /* shared: {
          ...dependencies,
        }, */
      },
    }
    return args
  })
 
  config.resolve.alias
  .set('vue$', 'vue/dist/vue.esm.js')
  .clear()
 
  //
  config.plugin('html').tap(args => {
    args[0] = {
      ...args[0],
      ...{
        title: 'EMP Vue Components',
        files: {
          js: ['http://localhost:8001/emp.js','http://code.jquery.com/jquery-1.9.1.min.js'

          ],
        },
      },
    }
    return args
  })
}

**Comment by longkehuawei** [comment]
麻烦帮忙看下

**Comment by flyyuan** [comment]
把 emp-config.js 改成
`
const withVue2 = require('@efox/emp-vue2')
module.exports = withVue2(({config}) => {
  const projectName = 'vue2Base'
  const port = 8009
  config.output.publicPath(`http://localhost:${port}/`)
  config.devServer.port(port)
  config.plugin('mf').tap(args => {
    args[0] = {
      ...args[0],
      ...{
        name: projectName,
        filename: 'emp.js',
        exposes: {
          './Content': './src/components/Content',
        },
        // shared: ['vue/dist/vue.esm.js'],
      },
    }
    return args
  })

  config.plugin('html').tap(args => {
    args[0] = {
      ...args[0],
      ...{
        title: 'EMP Vue2 Base',
      },
    }
    return args
  })
})

`
试试

**Comment by longkehuawei** [comment]
换成这样还是不行

(node:14204) UnhandledPromiseRejectionWarning: Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:373:10)
    at RuleSetCompiler.compileCondition (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:309:17)
    at ruleSetCompiler.hooks.rule.tap (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\BasicMatcherRulePlugin.js:29:40)
    at Hook.eval [as call] (eval at create (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:17:1)
    at RuleSetCompiler.compileRule (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:177:19)
    at rules.map (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:184:30)
    at rules.map (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:154:9)
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compile (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\rules\RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\NormalModuleFactory.js:226:34)
    at Compiler.createNormalModuleFactory (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:996:31)
    at Compiler.newCompilationParams (D:\vue\vue-demo\vue-demo2\hello\node_modules\@efox\emp-cli\node_modules\webpack\lib\Compiler.js:1016:30)
(node:14204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rej
ection id: 1)
(node:14204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<i> [webpack-dev-server] Project is running at http://127.0.0.1:8009/
<i> [webpack-dev-server] Content not from webpack is served from D:\vue\vue-demo\vue-demo2\hello\public
<i> [webpack-dev-server] 404s will fallback to /index.html
Starting server on http://localhost:8009
<i> [webpack-dev-middleware] wait until bundle finished: /

**Comment by flyyuan** [comment]
建议你还是把项目放到 codepen 或者 GitHub，否则复现不到你的问题

**Comment by longkehuawei** [comment]
我这传不了，就用你们的demo，你替换我给的package.json 和 emp-config.js 你那可以运行吗？

**Comment by flyyuan** [comment]
哪一个 demo

**Comment by longkehuawei** [comment]
https://blog.csdn.net/liyunkun888/article/details/102738377?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control&dist_request_id=&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-1.control

通过这个方式创建一个demo,然后替换我给的package.json 和emp-config.js 就能复现

**Comment by flyyuan** [comment]
你为什么不直接用 emp init 出来的 vue 项目呢？你这样做要自己适配 emp 会出现问题很正常

**Comment by longkehuawei** [comment]
我是已经有了项目，想集成emp，然后出错了，我就用这种方式创建一个demo，结果发现真的是这样，以有项目没发emp init 吧

**Comment by longkehuawei** [comment]
> 建议你还是把项目放到 codepen 或者 GitHub，否则复现不到你的问题
长传了demo    ，有时间帮忙看下，https://github.com/lanxingmo/hello-dev

**Comment by flyyuan** [comment]
刚刚我试了一下，你配置有点问题。
可以跟着我们的指引来改哈

**Comment by longkehuawei** [comment]
好的，我试试看啊

**Comment by longkehuawei** [comment]
又报了这个错
ERROR in ./src/components/HeaderSearch/index.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRule
Set-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/HeaderSearch/index.vue?vu
e&type=script&lang=js&) 26:0-24
Module not found: Error: Can't resolve 'path' in 'D:\demo_emp\toB\ui\src\components\HeaderSearch'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/components/HeaderSearch/index.vue?vue&type=script&lang=js& 1:0-208 1:224-227 1:229-434 1:229-434
 @ ./src/components/HeaderSearch/index.vue 2:0-57 3:0-52 3:0-52 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-lo
ader-options!./src/layout/components/Navbar.vue?vue&type=script&lang=js& 56:0-47 65:12-18
 @ ./src/layout/components/Navbar.vue?vue&type=script&lang=js& 1:0-209 1:225-228 1:230-436 1:230-436
 @ ./src/layout/components/Navbar.vue 2:0-58 3:0-53 3:0-53 10:2-8
 @ ./src/layout/components/index.js 2:0-45 2:0-45
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-lo
ader-options!./src/layout/index.vue?vue&type=script&lang=js& 20:0-76 27:13-20 28:12-18 30:14-22 31:13-20 32:14-22
 @ ./src/layout/index.vue?vue&type=script&lang=js& 1:0-202 1:218-221 1:223-422 1:223-422
 @ ./src/layout/index.vue 2:0-57 3:0-52 3:0-52 10:2-8
 @ ./src/store/modules/permission.js 4:0-36 57:26-32
 @ ./src/store/index.js 6:0-46 15:16-26
 @ ./src/bootstrap.js 10:0-28 76:9-14
 @ ./src/main.js 10:33-55

ERROR in ./src/layout/components/Sidebar/SidebarItem.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??cl
onedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/layout/components/Sidebar/Si
debarItem.vue?vue&type=script&lang=js&) 29:0-24
Module not found: Error: Can't resolve 'path' in 'D:\demo_emp\toB\ui\src\layout\components\Sidebar'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/layout/components/Sidebar/SidebarItem.vue?vue&type=script&lang=js& 1:0-220 1:236-239 1:241-458 1:241-458
 @ ./src/layout/components/Sidebar/SidebarItem.vue 2:0-63 3:0-58 3:0-58 9:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-lo
ader-options!./src/layout/components/Sidebar/index.vue?vue&type=script&lang=js& 29:0-40 33:17-28
 @ ./src/layout/components/Sidebar/index.vue?vue&type=script&lang=js& 1:0-214 1:230-233 1:235-446 1:235-446
 @ ./src/layout/components/Sidebar/index.vue 2:0-57 3:0-52 3:0-52 9:2-8
 @ ./src/layout/components/index.js 4:0-57 4:0-57
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-lo
ader-options!./src/layout/index.vue?vue&type=script&lang=js& 20:0-76 27:13-20 28:12-18 30:14-22 31:13-20 32:14-22
 @ ./src/layout/index.vue?vue&type=script&lang=js& 1:0-202 1:218-221 1:223-422 1:223-422
 @ ./src/layout/index.vue 2:0-57 3:0-52 3:0-52 10:2-8
 @ ./src/store/modules/permission.js 4:0-36 57:26-32
 @ ./src/store/index.js 6:0-46 15:16-26
 @ ./src/bootstrap.js 10:0-28 76:9-14
 @ ./src/main.js 10:33-55

ERROR in ./src/layout/components/TagsView/index.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedR
uleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/layout/components/TagsView/index.
vue?vue&type=script&lang=js&) 34:0-24
Module not found: Error: Can't resolve 'path' in 'D:\demo_emp\toB\ui\src\layout\components\TagsView'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/layout/components/TagsView/index.vue?vue&type=script&lang=js& 1:0-214 1:230-233 1:235-446 1:235-446
 @ ./src/layout/components/TagsView/index.vue 2:0-57 3:0-52 3:0-52 11:2-8
 @ ./src/layout/components/index.js 5:0-59 5:0-59
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-lo
ader-options!./src/layout/index.vue?vue&type=script&lang=js& 20:0-76 27:13-20 28:12-18 30:14-22 31:13-20 32:14-22
 @ ./src/layout/index.vue?vue&type=script&lang=js& 1:0-202 1:218-221 1:223-422 1:223-422
 @ ./src/layout/index.vue 2:0-57 3:0-52 3:0-52 10:2-8
 @ ./src/store/modules/permission.js 4:0-36 57:26-32
 @ ./src/store/index.js 6:0-46 15:16-26
 @ ./src/bootstrap.js 10:0-28 76:9-14
 @ ./src/main.js 10:33-55

webpack 5.15.0 compiled with 3 errors in 39631 ms

**Comment by flyyuan** [comment]
按改造指引的步骤，cli的项目应该可以跑起来的。这应该是你业务代码的问题

**Comment by longkehuawei** [comment]
改造后可以编译了,但是报了这个，找不到组件，啥原因呀？Uncaught (in promise) ReferenceError: HelloReact is not defined
    at Object../node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/App.vue?vue&type=script&lang=js& (App.vue:34)
    at __webpack_require__ (bootstrap:19)
    at Object../src/App.vue?vue&type=script&lang=js& (src_bootstrap_js.9a5ad17b.js:153)
    at __webpack_require__ (bootstrap:19)
    at Object../src/App.vue (src_bootstrap_js.9a5ad17b.js:117)
    at __webpack_require__ (bootstrap:19)
    at Module../src/bootstrap.js (src_bootstrap_js.9a5ad17b.js:52)
    at Function.__webpack_require__ (bootstrap:19)

**Comment by flyyuan** [comment]
把 app.vue 的 HelloReact 去掉

**Comment by longkehuawei** [comment]
主项目是vue ，子项目是react，怎样把react组件嵌入Vue主工程路由下面
