### ISSUE TITLE
emp+vue3，使用@efox/emp-compile-swc会出现presets错误

### ISSUE THREAD

**Issue by ycy1621260121** [efoxTeam/emp#340]
emp+vue3，使用@efox/emp-compile-swc会出现presets错误

**Comment by ckken** [comment]
有报错堆栈吗 可以发下 代码的github 地址

**Comment by ycy1621260121** [comment]
yarn run v1.22.19
$ emp dev
(node:21592) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'presets' of undefined
    at D:\hzx_work\business\business-center\node_modules\@efox\plugin-vue-3\dist\index.js:17:35
    at Object.tap (D:\hzx_work\business\business-center\node_modules\webpack-chain\src\Use.js:14:20)
    at PluginBabelVue3 (D:\hzx_work\business\business-center\node_modules\@efox\plugin-vue-3\dist\index.js:16:10)
    at D:\hzx_work\business\business-center\node_modules\@efox\emp\dist\config\plugins.js:15:27
    at Array.map (<anonymous>)
    at ConfigPlugins.setup (D:\hzx_work\business\business-center\node_modules\@efox\emp\dist\config\plugins.js:13:62)
    at exec (D:\hzx_work\business\business-center\node_modules\@efox\emp\dist\cli\index.js:52:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 5.97s.

**Comment by ckken** [comment]
vue 3 目前编译还是会有问题 ，有进展会进一步同步 可以先用 非 swc 版本

**Comment by ycy1621260121** [comment]
好的，谢谢大佬
