### ISSUE TITLE
vue-cli  现有项目接入emp报错

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#39]
╔════════════════════╤═══════════════╗
║ Emp & Deps         │ Version       ║
╟────────────────────┼───────────────╢
║ @efox/emp-cli      │ 1.6.5         ║
╟────────────────────┼───────────────╢
║ webpack            │ ^5.11.0       ║
╟────────────────────┼───────────────╢
║ webpack-dev-server │ ^4.0.0-beta.0 ║
╟────────────────────┼───────────────╢
║ typescript         │ ^4.0.5        ║
╟────────────────────┼───────────────╢
║ postcss            │ ^8.1.4        ║
╚════════════════════╧═══════════════╝

    (node:56470) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/Users/songtao/node_modules/webpack/lib/NormalModule.js:172:10)
    at /Users/songtao/Documents/df/backend/node_modules/@efox/emp-vue2/node_modules/vue-loader/lib/plugin-webpack5.js:36:70
    at Hook.eval [as call] (eval at create (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/lib/Compiler.js:988:26)
    at /Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/lib/Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/lib/Compiler.js:1024:28)
    at /Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/lib/Watching.js:112:19
    at _next0 (eval at create (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (/Users/songtao/Documents/df/backend/node_modules/@efox/emp-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56470) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ckken** [comment]
可以参考 https://github.com/efoxTeam/emp/tree/main/projects/vue2-project 后续考虑 做cli 迁移
